### ISSUE TITLE
Errors should be logged to file in addition to emailed

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#138]
The file path should be configurable as a variable in config.py.

**Comment by mutantmonkey** [comment]
There are a lot of unanswered questions here:
* What if someone doesn't want to log to a file? Are they supposed to just set the variable to empty or None, or is that not going to be allowed?
* Why should this be a variable in config.py instead of say, an environment variable?
* What about email logging? Does that need to be configurable to turn it on and off?
* What if someone wants to log to stderr or syslog?
* The current code doesn't really override the existing log handling, it simply adds an SMTPHandler; is it really appropriate to add custom log handling instead of letting uwsgi/gunicorn/whatever is running the site handle logging itself?

I'm kind of hesitant to just add another config option to config.py unless we can clearly define the need, why it makes sense to have this bizarre log path when there are no other paths in the config file, especially when it limits logging to a file.

**Comment by mutantmonkey** [comment]
It looks like logs are not actually going to the systemd journal right now. I would expect them to be, but I'll have to take a look at uwsgi configuration options.

**Comment by mutantmonkey** [comment]
With the changes in a5848ca8c84d4ac28ed398ec01beb07d40ea6022, logs are now going to syslog.
