### ISSUE TITLE
Mission control should validate fields

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#219]
for pledge, mandate phone number, address, _or_ email address

for stripe, mandate email

mandate address for all "ship me my premium" pledges

if any field is left blank, ensure it is entered as NULL in the DB.

**Comment by mutantmonkey** [comment]
We should not have to require email address for credit card donations; what if someone is calling instead of going online because they don't use a computer? In 88172329ffd3914d1915e256e411cd70d0bc73b1, I changed it so it can use an email address specified in the config as a default.

I don't think we should require phone number or email address for pledges and we definitely can't require address in any reasonable way of doing things.

I'm pretty sure address was already mandated for shipping premiums...have you seen any evidence pointing to the contrary?
