### ISSUE TITLE
Robot stream player doesn't work on Chrome for Android

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#35]
Clicking the play button doesn't work. However, http://engine.wuvt.vt.edu:8000/wuvt.ogg functions fine.

**Comment by mutantmonkey** [comment]
See if you can get Chrome's error log please.

**Comment by matthazinski** [comment]
How would I go about doing that?

**Comment by mutantmonkey** [comment]
I don't know, but I can't do any work on this without further information. I'm not going to run an Android emulator to test this, and the test for this is `audioTag.canPlayType('audio/ogg')`; if that returns false for Chrome on Android, this is not my problem.

**Comment by telnoratti** [comment]
https://developer.chrome.com/devtools/docs/remote-debugging It should be as simple as connecting an android device to a computer with chrome installed.

**Comment by mutantmonkey** [comment]
I tested on my phone earlier today and I found that it is indeed not working, even though the play button is not disabled. When you press it, it goes to the buffering state, but the play event is never fired and it never starts playing.

Apparently this is due to https://code.google.com/p/chromium/issues/detail?id=178297. At the very least it would be good to let people know it won't work in Chrome for Android. Maybe we could have a buffering timeout and direct people to another option if that's the case. Maybe the site needs a "Streaming Problems?" page that can provide assistance in situations like these, and also for people using IE.

**Comment by mutantmonkey** [comment]
I just had another thought: this might actually happen because we're creating a new audio tag with the autoplay element. Maybe it's not that Chrome issue, but the fact that it's autoplay. Could be worth calling .play() on it, just to see.

**Comment by mutantmonkey** [comment]
This isn't something I can fix. I'm just going to close this an mark as won't fix. I added a message if the stream doesn't start playing after 5 seconds in d49168ebacdf741841cecb0f87c797847cde2bf8, which is the best we can hope for I think.
