### ISSUE TITLE
Broken enumeration of charts for DJ

### ISSUE THREAD

**Issue by JasonDavidoff85** [wuvt/wuvt-site#402]
![enum](https://user-images.githubusercontent.com/19964109/134038674-5a34b6f7-14f2-4f85-b20b-0ab31c97d02c.JPG)

**Comment by mutantmonkey** [comment]
I'm not sure I understand this issue; this chart is for top albums by DJ (for Dr. Sue), and there are two different albums by The Beatles for positions 3 and 4. Can you please elaborate on what the expected behavior would be for this?

Link to the relevant page: https://www.wuvt.vt.edu/playlists/charts/dj/935/albums

**Comment by mutantmonkey** [comment]
Per discussion on Slack, closing this...
