### ISSUE TITLE
Trackman should have a timeout for automatically starting automation

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#44]
Some DJs forget to start automation, so we need to automatically start automation after 15 minutes or so. This needs to be done on the server side, either with a cron job or when automation submits a track.

**Comment by telnoratti** [comment]
I think doing this when automation submits a track would be best. It can check if there is a tracklog within 15 minutes, otherwise submit. There needs to be a button to disable this for DJs who play long tracks though. I imagine just setting a redis value "autologout_enabled" to false should suffice. This should be reset to true when a logout is detected.

**Comment by matthazinski** [comment]
We could also implement this in hardware :smile:

**Comment by telnoratti** [comment]
Unplug automation when you're not using it?

**Comment by matthazinski** [comment]
Nah, have a GPIO pin trigger automation metadata when the fader is on

**Comment by andreimarcu** [comment]
:+1:

**Comment by telnoratti** [comment]
This isn't a terrible idea is there an easy access to that? I assume this is how the "On Air" light works.
