### ISSUE TITLE
Scrobble to libre.fm

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#89]
Would be nice to have an alternative to last.fm

**Comment by mutantmonkey** [comment]
Please don't assign tasks like this to me, anyone can pick this sort of thing up. If we must use GitHub issues, I at least don't want tasks assigned to me that I may never work on.

**Comment by mutantmonkey** [comment]
I looked into this and libre.fm's site is pretty awful and doesn't seem widely used. In addition, pylast has libre.fm support, but it doesn't appear to work without an API key and secret, which is not possible to obtain as far as I can tell. If someone else wants to work on this, feel free to open, but I'm closing this as wontfix because I think it's not worth our time.
